### ISSUE TITLE
Allow setting the created date for environments

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#2463]
In order for billing data to be calculated correctly, we need to be able to set the `created` date for moved environments.

**Comment by justinlevi** [comment]
I believe this was solved in https://github.com/amazeeio/lagoon/commit/34d5f79e

**Comment by rocketeerbkw** [comment]
There was a regression in the commit of this issue from #2494 that means it's still not fixed in 2.x. I updated the original PR #2464 to fix it.
